### ISSUE TITLE
Des sites pour "jouer" entre élégance mathématique et implémentations

### ISSUE THREAD

**Issue by ChristopheVuong** [mycaule/functional-programming-and-maths#3]
Il y a des sites comme https://projecteuler.net qui donnent des problèmes qui peuvent se résoudre à la fois en cherchant des démonstrations et "astuces" mathématiques ou bien un programme informatique (de force brute à quelque chose de plus malin). Cela fait écho au problème posé https://github.com/mycaule/coding-interviews/tree/master/2020/mansuy.

 https://github.com/mycaule/functional-programming-and-maths/blob/9b35766c3b48365b00748a1e04c645e3976e3f4b/index.html#L169

**Comment by mycaule** [comment]
Merci pour la **très** bonne recommandation.

Yes d'ailleurs tu peux me recopier coller la formule pour factoriser 3^k-2^k stp ?

**Comment by ChristopheVuong** [comment]
L'idée est se ramener à ce qui ressemble le plus à un énoncé de théorème de Fermat (donc de se ramener à un 1 à droite de l'égalité modulo). On remarque que 2 x 19 = 38 = 1 [37], donc la ligne :
3^k = 2^k [37]
est équivalente à :
3^k x 19^k = (2 x 19)^k[37] car 19 et 37 sont premiers entre eux.
D'où (3 x 19)^k = 38^k = 1^k = 1 [37].
On a donc : 
(3 x 19)^k = 1 [37].
Après il suffit de remarquer que 57 = 20 [37], donc on arrive par transitivité de = à
20^k = 1 [37]
