### ISSUE TITLE
Caml

### ISSUE THREAD

**Issue by ChristopheVuong** [mycaule/functional-programming-and-maths#4]
En prépa, en option info en MP, je me rappelle que les gens faisaient du Caml (maintenu par l'Inria). C'est pas mal apparemment pour faire de la récursivité, à lier avec le principe de récurrence.

**Comment by mycaule** [comment]
Oui j'ai fait du Caml Light aussi et ça existe en Scala,
https://alvinalexander.com/scala/how-to-use-lists-nil-cons-scala-match-case-expressions/

Je compte utiliser la définition d'une suite récurrente
```
U0 = k
Un+1 = f(Un)
```

et montrer comment faire l'implémentation équivalente en Scala.
